[project]
name = "fanzadl"
version = "0.1.15"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.13.4", "requests>=2.34.2"]


[tool.uv]
package = true

[project.scripts]
fanzadl = "fanzadl.main:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "PLR2004", "COM812", "PLR0913"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]

[dependency-groups]
dev = [
    "ipykernel<7",
    "polyfactory>=3.3.0",
    "pytest>=9.0.3",
    "pytest-mock>=3.15.1",
]
